name: 'RamDrive'
description: "Virtual disk in RAM only"
inputs:
  drive:
    description: "New drive letter"
    required: true
    default: 'R'
    type: string
  size:
    description: "Drive maximal size"
    required: true
    default: '1GB'
    type: string
runs:
  using: "composite"
  steps:
  - shell: powershell
    run: |
      $ISCSIIP = (Get-NetIPAddress -AddressFamily IPv4 -AddressState Preferred)[0].IPAddress
      Install-WindowsFeature File-Services | Out-Null
      Install-WindowsFeature FS-iSCSITarget-Server | Out-Null
      Start-Service msiscsi
      Start-Service wintarget
      New-iscsivirtualdisk -path "ramdisk:RAMDISK1.vhdx" -Size $('${{ inputs.size }}' / ([UInt64]1)) | Out-Null
      New-IscsiServerTarget TargetRamdisk -InitiatorId IPAddress:$ISCSIIP | Out-Null
      Add-IscsiVirtualDiskTargetMapping -TargetName TargetRamdisk -Path ramdisk:RAMDISK1.vhdx -Lun 1 | Out-Null
      New-IscsiTargetPortal -TargetPortalAddress $ISCSIIP | Out-Null
      Get-IscsiTarget | Connect-IscsiTarget | Out-Null
      $ramD = Get-IscsiConnection | Get-Disk
      Set-Disk -InputObject $ramD -IsOffline $False
      Initialize-Disk -InputObject $ramD -PartitionStyle MBR
      New-Partition -InputObject $ramD -UseMaximumSize -DriveLetter "${{ inputs.drive }}"[0]
