name: 'RamDrive'
description: 'Virtual disk in RAM only, auto-adjusting its size to content.'
inputs:
  drive:
    description: 'Additionnal drive'
    required: true
    default: 'R:'
    type: string
runs:
  using: "composite"
  steps:
  - id: "Mounting_1-6"
    shell: powershell
    run: |
      Start-BitsTransfer "https://github.com/winfsp/winfsp/releases/download/v2.0/winfsp-2.0.23075.msi" "${env:TEMP}\winfsp.msi"
  - id: "Mounting_2-6"
    shell: powershell
    run: |
      Start-BitsTransfer "https://github.com/Ceiridge/WinFsp-MemFs-Extended/releases/download/v3.1/Memefs-Installer.exe" "${env:TEMP}\Memefs-Installer.exe"
  - id: "Mounting_3-6"
    shell: powershell
    run: |
      Start-Process -Wait 'msiexec' -ArgumentList '/i',"$($env:TEMP)\winfsp.msi",'/qn','/norestart','ADDLOCAL=F.Developer'
  - id: "Mounting_4-6"
    shell: powershell
    run: |
      Start-Process -Wait 'msiexec' -ArgumentList "$($env:TEMP)\Memefs-Installer.exe",'/S'
  - id: "Mounting_5-6"
    shell: powershell
    run: |
      Start-Process -Wait "${env:ProgramFiles(x86)}\WinFsp\bin\launchctl-x64.exe" -ArgumentList 'start','memefs64','ramdisk','""','\\.\${{ inputs.drive }}'
  - id: "Mounting_6-6"
    shell: powershell
    run: |
      Remove-Item "${env:TEMP}\winfsp.msi"
