name: 'RamDrive'
description: 'Virtual disk in RAM only, auto-adjusting its size to content.'
inputs:
  drive:
    description: 'Additionnal drive'
    required: true
    default: 'R:'
    type: string
runs:
  using: "composite"
  steps:
  - id: "Mounting"
    shell: powershell
    run: |
      Start-BitsTransfer "https://github.com/winfsp/winfsp/releases/download/v2.0/winfsp-2.0.23075.msi" "$($env:TEMP)\winfsp.msi"
      Start-Process -Wait "msiexec" -ArgumentList "/i ""$($env:TEMP)\winfsp.msi"" /qn /norestart ADDLOCAL=F.Developer"
      Net Use ${{ inputs.drive }} \\memfs64\Ramdrive
      Remove-Item "$($env:TEMP)\winfsp.msi"
