name: 'RamDrive'
description: 'Virtual disk in RAM only, auto-adjusting its size to content.'
inputs:
  drive:
    description: 'New drive letter'
    required: true
    default: 'R'
    type: string
  size:
    description: 'Drive maximal size'
    required: true
    default: '1GB'
    type: string
runs:
  using: "composite"
  steps:
  - shell: powershell
    run: |
      Install-WindowsFeature File-Services | Out-Null
      Install-WindowsFeature FS-iSCSITarget-Server | Out-Null
      Start-Service msiscsi
      Start-Service wintarget
      $ISCSIIP = (Get-NetIPAddress -AddressFamily IPv4 -AddressState Preferred)[0].IPAddress
      New-iscsivirtualdisk -path "ramdisk:RAMDISK1.vhdx" -Size "${{ inputs.size }}" | Out-Null
      New-IscsiServerTarget TargetRamdisk -InitiatorId IPAddress:$ISCSIIP | Out-Null
      Add-IscsiVirtualDiskTargetMapping -TargetName TargetRamdisk -Path ramdisk:RAMDISK1.vhdx -Lun 1 | Out-Null
      New-IscsiTargetPortal -TargetPortalAddress $ISCSIIP | Out-Null
      Get-IscsiTarget | Connect-IscsiTarget
      $ramD = Get-IscsiConnection
      $ramD | FL
      $ramD = ($ramD | Get-Disk)
      Set-Disk $ramD -IsOffline $False
      Initialize-Disk $ramD -PartitionStyle MBR
      New-Partition $ramD -UseMaximumSize -DriveLetter "${{ inputs.drive }}"[0]
